### ISSUE TITLE
Install is broken

### ISSUE THREAD

**Issue by glader** [whisklabs/airflow-clickhouse-plugin#18] opened 2020-05-25 13:37 UTC
Maybe I missed something significant, but I cannot install package via pip. It's very confusing for me, because someone should have stumbled upon this before.

```
# pip install -U airflow-clickhouse-plugin
Collecting airflow-clickhouse-plugin
  Downloading airflow-clickhouse-plugin-0.5.4.tar.gz (6.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/pip-egg-info
         cwd: /tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/setup.py", line 16, in <module>
        with open(os.path.join(here, 'requirements.txt')) as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-fqcwa4i2/airflow-clickhouse-plugin/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Any advice is welcome.

**Comment by bryzgaloff** [comment] 2020-05-25 14:03
Fixed by #19, please check. Now works for me. Initial issue is confirmed too.

**Closed** 2020-05-25 14:02 UTC

**Comment by glader** [comment] 2020-05-25 14:09
Thank you very much, it works.

**Comment by bryzgaloff** [comment] 2020-05-31 11:40
FYI I have [yanked](https://www.python.org/dev/peps/pep-0592/) broken release [0.5.4](https://pypi.org/project/airflow-clickhouse-plugin/0.5.4/).
